### ISSUE TITLE
Problem using audio augmentations with tensorflow

### ISSUE THREAD

**Issue by mcanan** [facebookresearch/AugLy#28] opened 2021-06-18 18:58 UTC
I tried to use the audio augmentations in a tensorflow project but I had a "Segmentation fault" error in running time while importing the modules.
In my case it can be reproduced only running these two lines:
```
import tensorflow
import augly.audio as audaugs
```

Versions:
```
tensorflow-gpu==2.4.1
augly==0.1.1
Python 3.8.5
```
Thank you

**Comment by jbitton** [comment] 2021-06-18 19:49
Hi @mcanan, thanks for reporting this -- looking into it. I assume that this is occurring because tensorflow & AugLy have conflicting dependencies. Will report back with updates once I'm able to reproduce + will hopefully have out a fix!

**Comment by hazirbas** [comment] 2021-06-18 20:23
@mcanan can you please check the `numpy` version? If you install `augly` after `tensorflow` it will upgrade the `numpy` version to `1.20.x` whereas `tensorflow` needs `1.19.x`.

**Comment by mcanan** [comment] 2021-06-18 21:11
After `augly` installation I have `numpy==1.20.2`.
I tried to downgrade to numpy `numpy==1.19.5` but got the same error (with `augly` warning saying it requires numpy version `1.20.X`)
I tried a new virtual environment installing `augly` first and then `tensorflow==2.4.1` and same error (with final numpy version `1.19.5`).
Thanks.

**Comment by hazirbas** [comment] 2021-06-18 21:13
@mcanan I cannot reproduce it on `conda python=3.7.5`, will give a shot on `python=3.8.5`

**Comment by iver56** [comment] 2021-06-18 21:16
@mcanan If you still struggle with this issue after a while, you might want to check out other Python libraries that to audio data augmentation. I've listed them here:
https://github.com/iver56/audiomentations#alternatives

**Comment by hazirbas** [comment] 2021-06-18 21:21
@mcanan I can confirm that it works for me on a `conda` environment with `python==3.8.5` and `tensorflow==2.4.1` but I wasn't able to install `tensorflow-gpu`, how do you install it?

**Comment by jbitton** [comment] 2021-06-18 21:37
Sorry for the delayed comment, @mcanan -- I tried to install `tensorflow-gpu` onto my gpu and ran into some issues as well; trying to resolve them. In any case, though, all of our unit tests for audio augmentations pass with numpy version 1.19.5 -- it should be fine to degrade the  `numpy` version on our side.

Will do some testing now to see if this will resolve the issue or if there are other packages that are conflicting (especially since you're getting the error no matter which `numpy` version you're using). I'll update the `requirements.txt` file accordingly after my findings :)

**Comment by mcanan** [comment] 2021-06-18 21:46
> @mcanan I can confirm that it works for me on a `conda` environment with `python==3.8.5` and `tensorflow==2.4.1` but I wasn't able to install `tensorflow-gpu`, how do you install it?

Thank you for the quick answer. In my case with `pip3 install tensorflow-gpu==2.4.1` on a machine with gpu.

**Comment by mcanan** [comment] 2021-06-18 21:47
> Sorry for the delayed comment, @mcanan -- I tried to install `tensorflow-gpu` onto my gpu and ran into some issues as well; trying to resolve them. In any case, though, all of our unit tests for audio augmentations pass with numpy version 1.19.5 -- it should be fine to degrade the `numpy` version on our side.
> 
> Will do some testing now to see if this will resolve the issue or if there are other packages that are conflicting (especially since you're getting the error no matter which `numpy` version you're using). I'll update the `requirements.txt` file accordingly after my findings :)

Thank you for the quick answer. Ok. I'll keep you updated if I found something new in my side.

**Comment by jbitton** [comment] 2021-06-18 22:13
Small update: Was able to reclone your environment using the following commands (using CentOS 8):
```
conda create --name test_tf python=3.8.5
conda activate test_tf
with-proxy conda install -c anaconda tensorflow-gpu=2.4.1
pip3 install augly
```

Opened a python interpreter, imported both libraries, but didn't get any segfault output:
```
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
2021-06-18 15:01:48.092147: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
>>> import augly.audio as audaugs
>>> 
```

Now, just because they're imported with no errors doesn't mean they necessarily work as expected, but you got errors *just* as soon as you imported, correct?

I will note that when I installed AugLy (post-tf) pip listed the dependency discrepancies. Note that out of this list only `numpy` is a toplevel dependency for AugLy (so most of these are likely dependencies for our dependencies):
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorboard 2.5.0 requires tensorboard-data-server<0.7.0,>=0.6.0, which is not installed.
tensorflow 2.4.1 requires flatbuffers~=1.12.0, but you have flatbuffers 20210226132247 which is incompatible.
tensorflow 2.4.1 requires gast==0.3.3, but you have gast 0.4.0 which is incompatible.
tensorflow 2.4.1 requires grpcio~=1.32.0, but you have grpcio 1.36.1 which is incompatible.
tensorflow 2.4.1 requires numpy~=1.19.2, but you have numpy 1.20.2 which is incompatible.
tensorflow 2.4.1 requires opt-einsum~=3.3.0, but you have opt-einsum 3.1.0 which is incompatible.
tensorflow 2.4.1 requires tensorflow-estimator<2.5.0,>=2.4.0, but you have tensorflow-estimator 2.5.0 which is incompatible.
aiohttp 3.6.3 requires chardet<4.0,>=2.0, but you have chardet 4.0.0 which is incompatible.
aiohttp 3.6.3 requires yarl<1.6.0,>=1.0, but you have yarl 1.6.2 which is incompatible.
```

Going to modify AugLy's `requirements.txt` locally and reinstall from setup to see if this list goes down. Will update.

**Comment by mcanan** [comment] 2021-06-18 22:48
In my case I am not using conda.
I am able to reproduce it from scratch in a new virtual environment (Ubuntu 20.04) with these commands:
```
python3 -m venv venv
source venv/bin/activate
pip3 install wheel
pip3 install tensorflow-gpu==2.4.1
pip3 install augly
python3 test.py
```
The content of `test.py` is:
```
import tensorflow
import augly.audio as audaugs
```

My output is:
```
2021-06-18 18:42:04.241048: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Segmentation fault (core dumped)
```
As an another difference with your environment, I am using CUDA 11.0.
Thank you

**Comment by hazirbas** [comment] 2021-06-19 00:11
So `conda` is able to find conflicting packages and provide some resolution. If you don't want to use `conda`, you can try [`pyenv virtualenv`](https://github.com/pyenv/pyenv-virtualenv) too. One more question I have is that do you happen to have this issue with other versions of `tensorflow-gpu`?

AugLy doesn't use CUDA right now so I do not think it is the core cause of this issue.

**Comment by jbitton** [comment] 2021-06-19 00:12
Hi @mcanan, thanks for the repro commands! I've been trying to find someone who has Ubuntu + CUDA 11.0 to repro these issues, but it seems like today I won't find someone (since it's the end of the work week). However, my intern has Ubuntu + CUDA 10.1, ran the exact commands you listed, but did not get a `segfault` (she did get another error though, because tensorflow-gpu v2.4.1 apparently requires CUDA >=11.0). 

My theory (so far) is that this error is occurring because of some c/c++ discrepancy either (a) between CUDA 10.1 & 11.0 or (b) between the way `tensorflow-gpu` is linked via `pip` versus via `conda`.

Here are two things to try in the meantime if you would like, otherwise I will try these myself once I get access to a machine with an identical to yours:

1. Try using a `conda` environment and install `tensorflow-gpu` via `conda` instead of `pip` and see if the issue persists
2. I doubt this is actually a pure python dependency discrepancy, but just in case I'm very wrong:

I just pushed a branch `change_reqs` (https://github.com/facebookresearch/AugLy/tree/change_reqs).
You can try to:
1. create a `venv` environment
2. pip install tensorflow-gpu
3. git clone `AugLy`
4. cd into `AugLy`
5. checkout my branch: `git checkout change_reqs`
5. run `python setup.py install`
6. try to import in your interpreter

I know this is a lot to ask, so definitely do not feel obligated to try this out. Worst case, I'll try on Monday (hopefully if I get access to a machine) :)

**Comment by mcanan** [comment] 2021-06-19 15:47
Thanks @jbitton, unfortunately to use `conda` at the moment is not a valid alternative for us.
I tried to install your new branch following your steps and I got the same `segfault`

As an update, yesterday as a workaround we were able to make it work, importing at the beginning of our project `torch` (but we are not using pytorch in our project):
```
import torch
import tensorflow
import augly.audio as audaugs
```

Now I tried to import first augly and then tensorflow and is also working. In this way:
```
import augly.audio as audaugs
import tensorflow
```
I don't know, but it seems some kind of conflict between pytorch dependencies and tensorflow dependencies.

Doing a:
```
strace python3 -c "import tensorflow; import augly.audio as audaugs"
```
The last file opened before the `segfault` is: `python3.8/site-packages/torchaudio/_internal/fft.py`. May be that gives you some clue.

Thank you

**Comment by jbitton** [comment] 2021-06-19 16:31
I'm glad you found a workaround (albeit unideal), but thank you so much for the additional info :) Will look into this and update you (likely on Monday)

**Comment by bhavdeep-saragadam** [comment] 2021-06-19 20:02
If you are using a windows pc. Then try running it on the administrator and then try installing the packages

**Comment by zpapakipos** [comment] 2021-06-21 09:07
Hi @mcanan, I submitted an issue to torchaudio about this since it seems to be caused by a dependency issue between torchaudio, tensorflow-gpu, & CUDA 11.0: https://github.com/pytorch/audio/issues/1595. Can you please comment on the issue with more details? For example, I left most of the questions about the environment blank since it's only happening on your environment, so you'll need to be the one to check versions etc.

**Comment by mcanan** [comment] 2021-06-21 12:57
Thank you @zpapakipos. I commented the issue with the details of my environment. Please let me know if you need additional information.

**Comment by zpapakipos** [comment] 2021-06-22 12:01
Hi @mcanan, we believe we have now fixed this issue by upgrading the version of torch & torchaudio in our requirements through this PR: https://github.com/facebookresearch/AugLy/pull/43. When you have a chance, can you `pip install -U augly` to get the new `augly 0.1.2` & make sure that the segfault no longer happens? Thanks!

**Comment by mcanan** [comment] 2021-06-22 13:17
I tested it and is working now. Thank you for all!

**Comment by jbitton** [comment] 2021-06-22 16:01
I am so happy to hear that!!! Gonna close this issue, feel free to reopen if you continue to experience any issue :)

**Closed by jbitton** 2021-06-22 16:01 UTC
